apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
  labels:
    application: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      application: demo-app
  template:
    metadata:
      labels:
        application: demo-app
    spec:
      containers:
      - name: demo-app
        image: index.docker.io/iconebhub/node-demo-app
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          timeoutSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
spec:
  ports:
  - nodePort: 31001
    targetPort: 3000
    port: 3000
    protocol: TCP
  selector:
    application: demo-app
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    application: demo-app
    version: v1
  name: demo-app-serviceip
spec:
  ports:
    - name: external
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    application: demo-app
    type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    application: demo-app
  name: demo-app
spec:
  rules:
    - host: demo-app.k8s.org1.fnebiolo.myinstance.com
      http:
        paths:
          - backend:
              serviceName: demo-app-serviceip
              servicePort: 80
# trigger spinnaker commit
